config/routes.rb
Rails.application.routes.draw do
  resources :articles do 
      post :action, :on => :collection
  end

  root 'welcome#index'
  post 'articles/action'

end

app/models/article.rb
class Article < ActiveRecord::Base
	# validates :title, presence: true,
	# 				  length: { minimum: 5 }

	validates :btype, presence: true,
					  length: { minimum: 5}
	validates :bvin, presence: true,
					  length: { minimum: 5}
  	validates :bweather, presence: true,
					  length: { minimum: 5}				  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	def new
  	end
  	def create
  		render plain: params[:article].inspect
  	end



  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
require 'fileutils'

class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end
	def edit
		@article = Article.find(params[:id])
	end
	def create
				puts "=========================================="
		puts "=========================================="
		puts "=========================================="
		puts params[:bvin]
				puts "=========================================="
		puts "=========================================="
		puts "=========================================="
		@article = Article.new(params[:article])

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	# def analysis
	# 	render 'analysis'
	# 	# system("C:/Users/35317/Documents/Energy Efficieny Analytics Team/blog/script/create_DOE_prototype_building/tests/create_DEO_prototypes_simplified_Testdp.rb")
		
	# 	# script/runner script/create_DOE_prototype_building/tests/create_DEO_prototypes_simplified_Testdp.rb
	# end

	def action
		puts "=========================================="
		puts "=========================================="
		puts "=========================================="
		puts params
		puts "=========================================="
		puts "=========================================="
		puts "=========================================="
		# input1 = "gui_selection_building_type = " + params[:btype]
		# input2 = "gui_selection_vintage = " + params[:bvin]
		# input3 = "gui_selection_weather = " + params[:bweather]
		# input1 = params['btype']
		# input2 = params['bvin']
		# input3 = params['bweather']
		inputs = ["gui_selection_building_type = 'Small Office'", "gui_selection_weather = 'Athens'", \
			"gui_selection_vintage = 'Post 1980'"]
		# inputs = [input1,input2,input3]
		finds = ["gui_selection_building_type =", "gui_selection_weather =","gui_selection_vintage ="]
		file_name = 'script/create_DOE_prototype_building/tests/create_DOE_prototypes_simplified_Testdp.rb'
		finds.each_with_index do |find, index|
			lines = IO.readlines(file_name).map do |line|
					if line.include? find
						inputs[index]
					else
						line
					end
			end

			File.open(file_name, 'w') do |file|
				file.puts lines
			end
		end


		system("ruby 'script/create_DOE_prototype_building/tests/create_DOE_prototypes_simplified_Testdp.rb'")
		oldname = 'script/create_DOE_prototype_building/tests/NewModel.osm'
		newname = 'script/create_DOE_prototype_building/tests/OldModel.osm'
		FileUtils.cp(oldname,newname)

		render 'analysis'
	end


	private
		def article_params
			params.require(:article).permit(:btype, :bvin, :bweather)			
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<!-- 	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %> -->

	<p>
		<%= f.select :btype, ['Secondary School','Small Office','Small Hotel'] %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/analysis.html.erb
<h1> Simulation Complete <h1>

app/views/articles/edit.html.erb
<h1> Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		>%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

<%= link_to 'Back', articles_path %>


app/views/articles/hide_index.html.erb
<h1> Listing Articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th colspan="2"></th>
	</tr>

	<% @articles.each do |article| %>
	<tr class="<%= cycle('list_line_odd','list_line_even') %>">
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= link_to 'Show', article_path(article) %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Destroy', article_path(article),
				method: :destroy,
				data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'Analysis', articles_action_path, method: :analysis %></td>
	</tr>
<% end %>
</table>
<br>
<%= button_to "Analysis", articles_action_path, method: :analysis %> 


app/views/articles/index.html.erb
<h1> GP EMS</h1>
<br>
<br>
<%= form_for :article, url: articles_path do |f| %>
	
	<%= f.label :'Building Type' %><br>
	<%= f.select :btype, ['','Secondary School','Small Office','Small Hotel'] %>
	<br>
	<br>
	<%= f.label :'Building Vintage' %><br>
	<%= f.select :bvin, ['','Pre 1980','Post 1980','New Construction'] %>
	<br>
	<br>
	<%= f.label :'Weather Station' %><br>
	<%= f.select :bweather, ['','Athens','Warner Robins','Valdosta Rgnl'] %>
	<br>
	<br>


<% end %>


<br>
<%= button_to "Analysis", articles_action_path, method: :analysis %> 


app/views/articles/new.html.erb
<h1>New Articles</h1>

<%# render 'form' %>

<%= link_to 'Back', articles_path %>

<%= form_for :article, url: articles_path do |f| %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :btype %><br>
    <%= f.text_field :btype %>
  </p>
 
<p>
    <%= f.label :bvin %><br>
    <%= f.text_area :bvin %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>


app/views/articles/show.html.erb
<p>
	<strong>Title: </strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', article_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>GP EMS</h1>
<%= link_to 'My Blog', controller: 'articles' %>